name: Run Selenium with Firefox

on: [push]

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4

    - name: Install compatible Firefox and GeckoDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox
        # Download and install the compatible geckodriver version
        wget https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
        tar -xzf geckodriver-v0.35.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/geckodriver

    - name: Run Selenium script
      run: |
        python app.py
