name: Test Requests

on:
  workflow_dispatch:
    inputs:
      request_url:
        description: 'URL to request'
        required: true
        default: 'https://upcar.up.gov.in/en/page/advisory'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Extract hostname
      id: extract_hostname
      run: |
        echo "Extracting hostname from URL"
        URL="${{ github.event.inputs.request_url }}"
        HOSTNAME=$(echo $URL | awk -F/ '{print $3}')
        echo "HOSTNAME=${HOSTNAME}" >> $GITHUB_ENV
        echo "Extracted hostname: ${HOSTNAME}"

    - name: Debug network environment
      run: |
        echo "Checking network connectivity to ${{ env.HOSTNAME }}"
        ping -c 4 ${{ env.HOSTNAME }} || true  # Try to ping the server
        nslookup ${{ env.HOSTNAME }} || true   # Try to resolve the DNS

    - name: Run test script
      env:
        REQUEST_URL: ${{ github.event.inputs.request_url }}
      run: python main.py
