name: Run Playwright with Firefox

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to be tested'
        required: true
        default: 'https://example.com'

jobs:
  playwright-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Adjust to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Playwright script
      run: |
        python test.py
      env:
        URL: ${{ github.event.inputs.url }}
